name: Build Tauri Windows

on:
  push:
    branches: [main] # dispara quando você fizer push na branch main

jobs:
  build-windows:
    runs-on: windows-latest # GitHub usa uma máquina Windows pra compilar

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Instalar dependências do projeto
        run: npm install

      - name: Build
        env:
          NUXT_PUBLIC_API_URL: https://sua-api.com # ← coloque sua URL aqui
        run: npx tauri build

      - name: Disponibilizar o instalador para download
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: src-tauri/target/release/bundle/
